### ISSUE TITLE
OT: Not a bug, a question about Wayland?

### ISSUE THREAD

**Issue by davidthewatson** [coddingtonbear/logitech-flow-kvm#2]
Hey @coddingtonbear 

Thanks for this! This is not a bug. Sorry to use github issues for such tomfoolery.

As a person who's used all manner of software KVM for twenty years and now finds himself in trouble given the combination of linux, mac, and windows on my desk, I was excited to find that my two decade habit of screen edging from one to the next was not finished, particularly since I run sway/wayland on linux. 

My question is simple: I've used solaar. I saw this bullet on their repo:

> Solaar will try to use uinput to simulate input from rules under Wayland or if Xtest is not available but this needs write permission on /dev/uinput. For more information see [the rules page](https://pwr-solaar.github.io/Solaar/rules).

Will logitech-flow-kvm work on wayland? If so, I'm headed to best buy to give it a run tonight. 

Any advice you can provide is seriously appreciated. My muscle memory is solid given the time, but I'm struggling given some neuropathy after years of falls while biking and running. 

If you have a patreon or some such, just tell me where it is and I'm happy to comply for the favor!

Cheers,
David

**Comment by coddingtonbear** [comment]
It does in fact work on Wayland, yes -- my needing to have a KVM solution on Wayland is in fact what drove me onto this path when I wrote this project.

That being said, I have some bad news for you: I'm not using this software at this point, so I can't make any solid guarantees about its performance, and I remember there being a handful of buggy edge cases I was never able to completely iron out.  These days, I've instead switched to just using https://github.com/htrefil/rkvm for my KVM needs.

Good luck!

**Comment by davidthewatson** [comment]
Thank you so much! 

That's pretty cool that logitech-flow-kvm works on wayland. I'm always happy to try and fix things, but given my need to purchase new devices, I think I'll give your suggestion of rkvm a try tonight, particularly since half my toolstack is already rust anyhow!

Thanks again!
